//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.MessageManager
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading;
    using Victop.Frame.CoreLibrary;
    using Victop.Frame.CoreLibrary.Models;
    using Victop.Frame.PublicLib.Helpers;

    /// <summary>
    /// 插件消息格式管理 【消息格式验证】
    /// </summary>
    /// <remarks>插件消息格式管理</remarks>
    public class PluginMessageFormManager
    {
        private delegate ReplyMessage ReturnImitativeReplyMessage(string msgId, string messageInfo);
        /// <summary>
        /// 检查插件消息格式
        /// <param name="messageInfo">消息信息</param>
        /// </summary>
        public virtual void CheckMessageFormat(string messageInfo, WaitCallback callBack)
        {
            PluginMessageManager pluginMessageManager = new PluginMessageManager();
            if (CheckMessageValid(messageInfo))//验证成功
            {
                RequestMessage message = new RequestMessage()
                {
                    MessageId = Guid.NewGuid().ToString(),
                    MessageType = JsonHelper.ReadJsonString(messageInfo, "MessageType"),
                    MessageContent = JsonHelper.ReadJsonString(messageInfo, "MessageContent")
                };
                bool result = pluginMessageManager.InsertPluginMessage(message.MessageId, new PluginMessageInfo()
                {
                    MessageBody = message,
                    MessageEffectiveTime = DateTime.Now.AddSeconds(15),
                    MessageId = message.MessageId,
                    CloudGalleryId = GalleryManager.GetCurrentGalleryId().ToString(),
                    MessageCallBack = callBack
                });
                if (result)//插入成功
                {
                    PluginMessageThreadManager.GetInstance().DoWork(message);
                }
                else
                {
                    ReturnReplyMessageToPlugin(messageInfo, callBack, CreateExsitRelyMessage);
                }
            }
            else//验证失败
            {
                ReturnReplyMessageToPlugin(messageInfo, callBack, CreateRelyMessage);
            }
        }

        private void ReturnReplyMessageToPlugin(string messageInfo, WaitCallback callBack, ReturnImitativeReplyMessage returnMsgDel)
        {
            RequestMessage message = CreateMessage(callBack);
            //1.调用自身方法创建对应的消息格式信息。
            ReplyMessage replyMessage = returnMsgDel(message.MessageId, messageInfo);
            //2.创建组织返回信息格式对象
            ReplyPluginMessageManager replyPluginMessageManager = new ReplyPluginMessageManager();
            //3.调用组织返回消息的方法。
            replyPluginMessageManager.OrganizeReplyMessage(replyMessage);
        }

        /// <summary>
        /// 验证/插入失败 创建消息，并插入消息池中
        /// </summary>
        /// <param name="callBack"></param>
        /// <param name="pluginMessageManager"></param>
        /// <returns></returns>
        private RequestMessage CreateMessage(WaitCallback callBack)
        {
            PluginMessageManager pluginMessageManager = new PluginMessageManager();
            RequestMessage message = new RequestMessage()
            {
                MessageId = Guid.NewGuid().ToString()
            };
            bool result = pluginMessageManager.InsertPluginMessage(message.MessageId, new PluginMessageInfo()
            {
                MessageBody = message,
                MessageEffectiveTime = DateTime.Now.AddSeconds(15),
                MessageId = message.MessageId,
                MessageCallBack = callBack
            });
            return message;
        }
        /// <summary>
        /// 验证消息格式的完整性
        /// </summary>
        /// <param name="messageInfo"></param>
        /// <returns></returns>
        private bool CheckMessageValid(string messageInfo)
        {
            //TODO : 根据消息类型MessageType判断MessageContent中参数是否完整.
            if (string.IsNullOrEmpty(JsonHelper.ReadJsonString(messageInfo, "MessageType")) || string.IsNullOrEmpty(JsonHelper.ReadJsonString(messageInfo, "MessageContent")))
            {
                return false;
            }
            return true;
        }

        /// <summary>
        ///验证失败， 创建应答消息对象。
        /// </summary>
        /// <param name="messageInfo"></param>
        /// <returns></returns>
        private ReplyMessage CreateRelyMessage(string messageId, string messageInfo)
        {
            ReplyMessage replyMessage = new ReplyMessage();//创建应答消息对象。
            replyMessage.MessageId = messageId;
            replyMessage.ReplyAlertMessage = "消息格式有误";
            replyMessage.ReplyContent = "[{\"ReplyData\":\"失败\"}]";
            return replyMessage;
        }

        /// <summary>
        /// 消息已存在时，创建应答消息对象。
        /// </summary>
        /// <param name="messageInfo"></param>
        /// <returns></returns>
        private ReplyMessage CreateExsitRelyMessage(string messageId, string messageInfo)
        {
            ReplyMessage replyMessage = new ReplyMessage();//创建应答消息对象。
            replyMessage.MessageId = messageId;
            replyMessage.ReplyAlertMessage = "消息已存在";
            replyMessage.ReplyContent = "[{\"ReplyData\":\"消息已存在\"}]";
            return replyMessage;
        }

    }
}

