//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.MessageManager
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Victop.Frame.Connection;
    using Victop.Frame.CoreLibrary.Models;
    using Victop.Frame.Connection;
    using Victop.Frame.CoreLibrary;
    /// <summary>
    /// 请求消息发送【消息发送】
    /// </summary>
    /// <remarks>请求消息发送</remarks>
    public class RequestMessageSend
    {
        /// <summary>
        /// 请求消息体发送
        /// </summary>
        /// <param name="messageInfo">请求消息体</param>
        public virtual void SendMessage(RequestMessage messageInfo)
        {
            MessageBodyManager messageBodyManager = new MessageBodyManager();
            ReplyMessage replyMessage = messageBodyManager.SendMessage(messageInfo);
            PluginMessageManager pluginMsgManager = new PluginMessageManager();
            //取得消息列表
            if ( pluginMsgManager.CheckMessageIsExist(messageInfo.MessageId))
            {
                ReplyPluginMessageManager replyManager = new ReplyPluginMessageManager();
                replyManager.OrganizeReplyMessage(replyMessage);
            }
        }

    }
}

