//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.CoreLibrary.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Victop.Frame.CoreLibrary.Enums;

	/// <summary>
	/// 活动插件信息
	/// </summary>
	/// <remarks>活动插件信息</remarks>
	public class ActivePluginInfo
	{
        private string appId;
		/// <summary>
		/// 插件标识
		/// </summary>
		public virtual string AppId
		{
            get { return appId; }
            set { appId = value; }
		}
        private string objectId;
		/// <summary>
		/// 对象标识
		/// </summary>
		public virtual string ObjectId
		{
            get { return objectId;}
            set { objectId = value; }
		}
        private string businessKey;
		/// <summary>
		/// 业务信息标识
		/// </summary>
		public virtual string BusinessKey
		{
            get { return businessKey; }
            set { businessKey = value; }
		}
        private GalleryEnum cloudGalleryId;
		/// <summary>
		/// 云通道标识
		/// </summary>
        public virtual GalleryEnum CloudGalleryId
		{
            get { return cloudGalleryId; }
            set { cloudGalleryId = value; }
		}

        private int showType;
		/// <summary>
		/// 显示类型
		/// </summary>
		public virtual int ShowType
		{
            get { return showType; }
            set { showType = value; }
		}

        private object pluginInstance;
        /// <summary>
        /// 插件实例
        /// </summary>
        public object PluginInstance
        {
            get { return pluginInstance; }
            set { pluginInstance = value; }
        }

	}
}

