//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.CoreLibrary.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Text;
    using Victop.Frame.CoreLibrary.Models;
    using Victop.Frame.CoreLibrary.Enums;
    using Victop.Frame.CoreLibrary.MongoModel;

    /// <summary>
    /// 数据通道数据类
    /// </summary>
    /// <remarks>数据通道数据类</remarks>
    public class ChannelData
    {
        /// <summary>
        /// 数据信息
        /// </summary>
        public virtual DataSet DataInfo
        {
            get;
            set;
        }

        /// <summary>
        /// 消息信息(查询条件)
        /// </summary>
        public virtual RequestMessage MessageInfo
        {
            get;
            set;
        }
        /// <summary>
        /// JSON数据信息
        /// </summary>
        public virtual string JSONData
        {
            get;
            set;
        }
        /// <summary>
        /// 原始JSON数据信息
        /// </summary>
        public virtual string OriginalJsonData
        {
            get;
            set;
        }

        /// <summary>
        /// 调整的JSON数据信息
        /// </summary>
        public virtual List<object> CrudJSONData
        {
            get;
            set;
        }
        /// <summary>
        /// 模型定义信息
        /// </summary>
        public MongoModelInfoModel ModelDefInfo
        {
            get;
            set;
        }
        /// <summary>
        /// 简单引用信息
        /// </summary>
        public MongoSimpleRefInfoModel SimpleRefInfo
        {
            get;
            set;
        }
        /// <summary>
        /// 数据权限
        /// </summary>
        public virtual string DatapermString
        {
            get;
            set;
        }
    }
}

