//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.CoreLibrary.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 菜单信息
	/// </summary>
	/// <remarks>菜单信息</remarks>
	public class MenuInfo
	{
        #region 注册连接器获取的菜单结构
        /// <summary>
        /// 菜单标识
        /// </summary>
        public string Id
        {
            get;
            set;
        }

        /// <summary>
        /// SystemId
        /// </summary>
        public string BzSystemId
        {
            get;
            set;
        }

        /// <summary>
        /// 终节点信息
        /// </summary>
        public string EndPoint
        {
            get;
            set;
        }

        /// <summary>
        /// 菜单id
        /// </summary>
        public string MenuId
        {
            get;
            set;
        }

        /// <summary>
        /// 菜单名称
        /// </summary>
        public string MenuName
        {
            get;
            set;
        }

        /// <summary>
        /// FormId
        /// </summary>
        public string FormId
        {
            get;
            set;
        }

        /// <summary>
        /// 父级菜单
        /// </summary>
        public string ParentMenu
        {
            get;
            set;
        }

        /// <summary>
        /// 是否激活
        /// </summary>
        public int Actived
        {
            get;
            set;
        }

        /// <summary>
        /// 备注
        /// </summary>
        public string Memo
        {
            get;
            set;
        }

        /// <summary>
        /// 自动打开标识
        /// </summary>
        public int AutoOpenFlag
        {
            get;
            set;
        }

        /// <summary>
        /// 时间戳
        /// </summary>
        public DateTime Stamp
        {
            get;
            set;
        }

        /// <summary>
        /// 显示方式
        /// </summary>
        public int DisplayType
        {
            get;
            set;
        }

        /// <summary>
        /// 打开方式
        /// </summary>
        public int OpenType
        {
            get;
            set;
        }

        public string Compatible
        {
            get;
            set;
        }

        /// <summary>
        /// 终结点参数
        /// </summary>
        public string EndPointParam
        {
            get;
            set;
        }

        /// <summary>
        /// 主目录Id
        /// </summary>
        public string HomeId
        {
            get;
            set;
        }

        /// <summary>
        /// 队序
        /// </summary>
        public int Sequence
        {
            get;
            set;
        }

        /// <summary>
        /// Form名称
        /// </summary>
        public string FormName
        {
            get;
            set;
        }

        /// <summary>
        /// Form描述
        /// </summary>
        public string FormMemo
        {
            get;
            set;
        }

        /// <summary>
        /// 数据FormId
        /// </summary>
        public string DataFormId
        {
            get;
            set;
        }

        /// <summary>
        /// 前置文档属性
        /// </summary>
        public string PredocStatus
        {
            get;
            set;
        }

        /// <summary>
        /// 文档状态
        /// </summary>
        public string DocStatus
        {
            get;
            set;
        }

        /// <summary>
        /// 默认打印模版
        /// </summary>
        public string DefaultPrintTemplate
        {
            get;
            set;
        }

        /// <summary>
        /// 资源类型
        /// </summary>
        public string ResourceType
        {
            get;
            set;
        }

        /// <summary>
        /// 资源名称
        /// </summary>
        public string ResourceName
        {
            get;
            set;
        }

        /// <summary>
        /// 资源树
        /// </summary>
        public string ResourceTree
        {
            get;
            set;
        }

        /// <summary>
        /// 最大打印数量
        /// </summary>
        public string MaxPrintCount
        {
            get;
            set;
        }

        /// <summary>
        /// 保存解决方案
        /// </summary>
        public string SaveProject
        {
            get;
            set;
        } 
        #endregion

        #region Mongo独立取菜单的结构
        public string _id;
        public string systemid;
        public string parent_id;
        public string client_type_val;
        public string client_type_txt;
        public string menu_no;
        public string menu_name;
        public string url;
        public string icon;
        public string is_single;
        public string authority_code;
        public string priority;
        public string menuCode;
        #endregion

    }
}

