//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.CoreLibrary.Enums
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    public enum DataOperateEnum
    {
        /// <summary>
        /// 无操作
        /// </summary>
        NONE,
        /// <summary>
        /// 保存数据
        /// </summary>
        SAVE,
        /// <summary>
        /// 提交数据
        /// </summary>
        COMMIT,
        /// <summary>
        /// 取消
        /// </summary>
        CANNEL
    }
}
