//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.CoreLibrary.Enums
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 通道枚举类
	/// </summary>
	public enum GalleryEnum
	{
		/// <summary>
		/// 本地SOA
		/// </summary>
		LOCALSOA,
		/// <summary>
		/// 飞道云
		/// </summary>
		VICTOP,
		/// <summary>
		/// 企业云
		/// </summary>
		ENTERPRISE,
	}
}
