//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.CoreLibrary.Enums
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 消息目标类型枚举
	/// </summary>
	/// <remarks>消息目标类型枚举</remarks>
	public enum MessageTargetEnum : int
	{
		/// <summary>
		/// 常规消息
		/// </summary>
		NORMAL,
		/// <summary>
		/// 主服务
		/// </summary>
		MAIN,
		/// <summary>
		/// 连接器
		/// </summary>
		LINK,
	}
}
