//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.CoreLibrary.Enums
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 消息线程状态枚举
	/// </summary>
	/// <remarks>消息线程状态枚举</remarks>
	public enum ThreadStatusEnum
	{
		WAITE,
		SEND,
	}
}
