//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.CoreLibrary
{
	using Victop.Frame.CoreLibrary.Models;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Victop.Frame.CoreLibrary.Enums;

	/// <summary>
	/// 基础资源管理
	/// </summary>
	/// <remarks>基础资源管理</remarks>
	public class BaseResourceManager
	{
		/// <summary>
		/// 添加基础资源
		/// </summary>
		public virtual bool AddResouce(BaseResourceInfo baseResouce)
		{
            if (baseResouce == null)
                return false;
            if (CoreDataCollection.BaseResourceList.ContainsKey(baseResouce.GalleryId.ToString()))
            {
                CoreDataCollection.BaseResourceList.Remove(baseResouce.GalleryId.ToString());
                CoreDataCollection.BaseResourceList.Add(baseResouce.GalleryId.ToString(), baseResouce);
            }
            else
            {
                CoreDataCollection.BaseResourceList.Add(baseResouce.GalleryId.ToString(), baseResouce);
            }
            return true;
		}

		/// <summary>
		/// 根据通道标识获取基础资源信息
		/// </summary>
		private BaseResourceInfo GetResouce(string cloudGalleryId)
		{
            if (CoreDataCollection.BaseResourceList.ContainsKey(cloudGalleryId))
            {
                return CoreDataCollection.BaseResourceList[cloudGalleryId];
            }
            else
            {
                return null;
            }
		}

		/// <summary>
		/// 根据通道标识移除通道资源
		/// </summary>
		public virtual bool RemoveResource(string cloudGalleryId)
		{
            if (CoreDataCollection.BaseResourceList.ContainsKey(cloudGalleryId))
            {
                CoreDataCollection.BaseResourceList.Remove(cloudGalleryId);
                return true;
            }
            else
            {
                return false;
            }
		}
        /// <summary>
        /// 获取全部基础资源信息
        /// </summary>
        /// <returns></returns>
        public Dictionary<string, BaseResourceInfo> GetAllBaseResource()
        {
            return CoreDataCollection.BaseResourceList;
        }
        /// <summary>
        /// 获取当前通道基础资源
        /// </summary>
        /// <returns></returns>
        public BaseResourceInfo GetCurrentGalleryBaseResource()
        {
            GalleryEnum galleryId = GalleryManager.GetCurrentGalleryId();
            return GetResouce(galleryId.ToString());
        }

	}
}

