//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.CoreLibrary
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 框架关闭(废弃)
	/// </summary>
	/// <remarks>框架卸载</remarks>
	public class FrameUnload
	{
		public virtual bool MessageComLinkClose()
		{
			throw new System.NotImplementedException(); 
		}

		public virtual void CleanSystemData()
		{
			throw new System.NotImplementedException(); 
		}

	}
}

