//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.ComLink.ICE.Maps
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 队列条目
	/// </summary>
	/// <remarks>队列条目</remarks>
	public class QueueEntry
	{
        private string name;
		/// <summary>
		/// 名称
		/// </summary>
		public string Name
		{
            get { return name; }
            set { name = value; }
		}

        private long size;
		/// <summary>
		/// 大小
		/// </summary>
		public long Size
		{
            get { return size; }
            set { size = value; }
		}

        private Queue<object> entries;
		/// <summary>
		/// 条目
		/// </summary>
		public Queue<object> Entries
		{
            get
            {
                if (entries == null)
                    entries = new Queue<object>();
                return entries;
            }
            set
            {
                entries = value;
            }
		}

	}
}

