//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.ServerManagerCenter
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 分支标识枚举
	/// </summary>
	public enum RamifyEnum
	{
		/// <summary>
		/// 运行
		/// </summary>
		RUN,
		/// <summary>
		/// 检查
		/// </summary>
		CHECK,
	}
}
