//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.ServerManagerCenter
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 服务侦听器(暂不开发)
	/// </summary>
	/// <remarks>服务侦听器</remarks>
	public class ServerListener
	{
		/// <summary>
		/// 服务侦听初始化
		/// </summary>
		public virtual void ServerListenInit()
		{
			throw new System.NotImplementedException(); //TODO:方法实现
		}

		/// <summary>
		/// 开启服务侦听
		/// </summary>
		public virtual void StartServerListen()
		{
			throw new System.NotImplementedException(); //TODO:方法实现
		}

		/// <summary>
		/// 停止服务侦听
		/// </summary>
		public virtual void StopServerListen()
		{
			throw new System.NotImplementedException(); //TODO:方法实现
		}

	}
}

