//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.ComLink.ICE.Servants
{
    using Ice;
    using slice;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

	/// <summary>
	/// 服务参数
	/// </summary>
	/// <remarks>服务参数</remarks>
	public class ServiceParams
	{
		/// <summary>
		/// 回调
		/// </summary>
		public AMD_MessageEndpoint_sendMessage CallBack
		{
			get;
			set;
		}
        /** ICE应答. */
        public AMD_MessageEndpoint_sendMessageNew NewCallBack
        {
            get;
            set;
        }
		/// <summary>
		/// 是否回调
		/// </summary>
		public bool IsCallBack
		{
			get;
			set;
		}

		/// <summary>
		/// 当前ICE
		/// </summary>
		public Current ICE_Current
		{
			get;
			set;
		}

		/// <summary>
		/// 通信上下文
		/// </summary>
		public string Hash
		{
			get;
			set;
		}
        private Message message;

        public Message Message
        {
            get { return message; }
        }

        public ServiceParams(AMD_MessageEndpoint_sendMessageNew cb, Message message, bool isCallback, string hash, Current current)
        {
            this.NewCallBack = cb;
            this.IsCallBack = isCallback;
            this.ICE_Current = current;
            this.Hash = hash;
            this.message = message;
        }

		/// <summary>
		/// 初始化服务参数
		/// </summary>
		public ServiceParams(AMD_MessageEndpoint_sendMessage cb, bool isCallBack, string hash, Current current)
		{
            this.CallBack = cb;
            this.IsCallBack = isCallBack;
            this.ICE_Current = current;
            this.Hash = hash;
		}

	}
}

