//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.CoreLibrary.Interfaces
{
    using Models;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Text;

    /// <summary>
    /// 数据操作接口
    /// </summary>
    /// <remarks>数据通道操作接口</remarks>
    public interface IFeiDaoDataOperation
    {
        #region 数据操作
        /// <summary>
        /// 数据库初始化
        /// </summary>
        /// <returns>初始化结果 true:成功,false:失败</returns>
        bool DataBaseInit();
        /// <summary>
        /// 插入数据
        /// </summary>
        /// <param name="newEntity">指定对象</param>
        /// <returns>执行成功返回true,否则为false</returns>
        bool Insert(FeiDaoDBModel newEntity);

        /// <summary>
        /// 更新对象属性到数据库中
        /// </summary>
        /// <param name="updateEntity">指定的对象</param>
        /// <param name="key">主键的值</param>
        /// <returns>执行成功返回true,否则为false</returns>
        bool Update(FeiDaoDBModel updateEntity, string key);

        /// <summary>
        /// 根据指定对象的ID，从数据库中删除指定对象
        /// </summary>
        /// <param name="id">对象ID</param>
        /// <returns>执行成功返回true,否则为false</returns>
        bool Delete(string id);
        #endregion
        #region 数据查询
        /// <summary>
        /// 查询数据库，返回指定ID的对象
        /// </summary>
        /// <param name="id">ID主键的值</param>
        /// <returns>存在则返回指定的对象，否则返回null</returns>
        FeiDaoDBModel FindByID(string id);
        /// <summary>
        /// 依据条件查询数据
        /// </summary>
        /// <param name="pluginName">插件名称</param>
        /// <param name="paramName">参数名称</param>
        /// <returns></returns>
        FeiDaoDBModel FindByCondtion(string pluginName, string paramName);
        #endregion
    }
}

