package AutomaticCodePlugin

import Victop.Server.Controls;
import Victop.Server.Controls.Models;
import Victop.Frame.CmptRuntime;

global Victop.Frame.CmptRuntime.FeiDaoOperation FeiDao

rule RecurseLoad
	agenda-group "load"
	salience 10
	when
		se : StateTransitionModel ()
	then
		FeiDao.SysConsole("BtnOpViewRules:"+se.ActionTrigger);
		FeiDao.SysConsole("BtnOpViewRules:"+se.ActionDestination);
		FeiDao.InsertFact(new OAVModel("a","a","true"));
end

rule RecurseSearch
	agenda-group "search"
	salience 10
	when
		se : StateTransitionModel ()
		o1:  OAVModel(ObjectName=="a",AtrributeName=="a",AtrributeValue=="true")
	then
		
		FeiDao.ExcutePageTrigger("search",se.ActionSourceElement);
		FeiDao.SetButtonText("saveBtn",se.ActionDestination);
		FeiDao.SysConsole("BtnOpViewRules:"+se.ActionTrigger);
		FeiDao.SysConsole("BtnOpViewRules:"+se.ActionDestination);
end