rule "r2" {salience: 1;agenda-group: "afterinit";when{a:OAV a.o=="event_parameter"&&a.a=="1";} then{feidao.SysConsole("DataGridView:afterinit");}}
rule "r3" 
{
	salience: 10;
	agenda-group: "search";
	when
	{
		a:OAV a.o=="event_parameter"&&a.a=="1";
	}
	then
	{
		feidao.GetPBlockData("masterPBlock");
		feidao.oav_insert("param","productid");
	}
}
rule "r3_1" 
{
	salience: 9;
	agenda-group: "search";
	when
	{
		a:OAV a.o=="event_parameter"&&a.a=="1";
		o2:OAV o2.o=="param"&&o2.a==="productid";
	}
	then
	{
		feidao.ParamsInterCompntParse(a,"productid",o2);
		feidao.GetPBlockData("masterPBlock");
		feidao.oav_remove(a);
		feidao.oav_remove(o2);
	}
}