package AutomaticCodePlugin

import Victop.Server.Controls.Models;
import Victop.Frame.CmptRuntime;

global Victop.Frame.CmptRuntime.FeiDaoOperation FeiDao

rule RecurseLoaded
	agenda-group "load"
	salience 10
	when
		se : StateTransitionModel ()
	then
		FeiDao.SysConsole("DataGridViewRules:"+se.ActionTrigger);
		FeiDao.SysConsole("DataGridViewRules:"+se.ActionDestination);
		FeiDao.SetFocus("search");
end

rule RecurseSearched
	agenda-group "search"
	salience 10
	when
		se : StateTransitionModel ()
	then
		FeiDao.GetPBlockData("masterPBlock");
		FeiDao.SysConsole("DataGridViewRules:"+se.ActionTrigger);
		FeiDao.SysConsole("DataGridViewRules:"+se.ActionDestination);
end