package AutomaticCodePlugin

import Victop.Server.Controls.Models;
import Victop.Frame.CmptRuntime;

global Victop.Frame.CmptRuntime.FeiDaoOperation FeiDao

rule RecurseSearch
	agenda-group "search"
	salience 10
	when
		se : StateTransitionModel ()
	then
		FeiDao.ExcuteComponentTrigger("ucdgrid","search",se.ActionSourceElement);
		FeiDao.SysConsole("MainViewRules:"+se.ActionTrigger);
		FeiDao.SysConsole("MainViewRules:"+se.ActionDestination);
end