//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.Connection
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Victop.Frame.CoreLibrary.Models;
    using Victop.Frame.Adapter;
    using Victop.Frame.CoreLibrary.Interfaces;
    using Victop.Frame.CoreLibrary.Enums;
    using Victop.Frame.PublicLib.Helpers;
    using Victop.Frame.CoreLibrary;
    using Victop.Frame.PublicLib.Managers;
    using System.Configuration;
    using System.Net;
    using System.Text.RegularExpressions;

    /// <summary>
    /// 消息转发器
    /// </summary>
    /// <remarks>消息转发器</remarks>
    public class MessageTransmitManager
    {
        /// <summary>
        /// 发送消息
        /// </summary>
        public virtual ReplyMessage SendRmoteMessage(RequestMessage messageInfo)
        {
            IAdapter adapter = new MessageManager();
            try
            {
                if (messageInfo.MessageType.Equals("LoginService.userLogin"))
                {
                    ReplyMessage replyMessage = UserLoginSubmit(adapter, messageInfo);
                    return replyMessage;
                }
                if (messageInfo.MessageType.Equals("MongoDataChannelService.loginout"))
                {
                    ReplyMessage replyMessage = UserLoginOutSubmit(adapter, messageInfo);
                    return replyMessage;

                }
                else if (messageInfo.MessageType.Equals("MongoDataChannelService.getuserauthInfo"))
                {

                    DataOperateEnum saveDataFlag = DataOperateEnum.NONE;
                    MessageOrganizeManager organizeManager = new MessageOrganizeManager();
                    messageInfo = organizeManager.OrganizeMessage(messageInfo, out saveDataFlag);
                    ReplyMessage replyMessage = GetUserMenuInfoSubmit(adapter, messageInfo);
                    return replyMessage;
                }
                else
                {
                    ReplyMessage replyMessage = MessageSubmit(adapter, messageInfo);
                    if (replyMessage.ReplyMode == ReplyModeEnum.ROUTER)
                    {
                        RequestMessage userLoginMsg = new RequestMessage();
                        userLoginMsg.MessageType = "LoginService.userLogin";
                        CloudGalleryInfo currentGallery = new GalleryManager().GetGallery(GalleryManager.GetCurrentGalleryId().ToString());
                        Dictionary<string, object> loginContent = new Dictionary<string, object>();
                        loginContent.Add("usercode", currentGallery.ClientInfo.UserCode);
                        loginContent.Add("userpw", currentGallery.ClientInfo.UserPwd);
                        loginContent.Add("logintypenew", GetUserLoginForm(currentGallery.ClientInfo.UserCode));
                        userLoginMsg.MessageContent = JsonHelper.ToJson(loginContent);
                        ReplyMessage loginReplyMessage = UserLoginSubmit(adapter, userLoginMsg);
                        if (loginReplyMessage.ReplyMode != ReplyModeEnum.CAST)
                        {
                            replyMessage = MessageSubmit(adapter, messageInfo);
                        }
                        else
                        {
                            replyMessage = loginReplyMessage;
                            replyMessage.ReplyMode = ReplyModeEnum.CAST;
                        }
                    }
                    return replyMessage;
                }
            }
            catch (Exception ex)
            {
                LoggerHelper.Info(messageInfo, ex);
                ReplyMessage replyMessage = new ReplyMessage()
                {
                    MessageId = messageInfo.MessageId,
                    ReplyContent = ex.InnerException == null ? ex.Message : ex.InnerException.Message
                };

                return replyMessage;
            }
        }

        private ReplyMessage UserLoginOutSubmit(IAdapter adapter, RequestMessage messageInfo)
        {
            Dictionary<string, string> contentDic = JsonHelper.ToObject<Dictionary<string, string>>(messageInfo.MessageContent);
            if (!contentDic.ContainsKey("systemid"))
            {
                contentDic.Add("systemid", ConfigurationManager.AppSettings["clientsystem"]);
            }
            messageInfo.MessageContent = JsonHelper.ToJson(contentDic);
            MessageOrganizeManager organizeManager = new MessageOrganizeManager();
            DataOperateEnum saveDataFlag = DataOperateEnum.NONE;
            messageInfo = organizeManager.OrganizeMessage(messageInfo, out saveDataFlag);
            ReplyMessage replyMessage = adapter.SubmitRequest(messageInfo);
            replyMessage.MessageId = messageInfo.MessageId;
            if (replyMessage.ReplyMode != (ReplyModeEnum)0)
            {
                CloudGalleryInfo currentGallery = new GalleryManager().GetGallery(GalleryManager.GetCurrentGalleryId().ToString());
                currentGallery.IsLogin = false;
                currentGallery.ClientInfo.SessionId = string.Empty;
                currentGallery.ClientInfo.UserName = string.Empty;
                currentGallery.ClientInfo.UserCode = string.Empty;
            }
            return replyMessage;
        }

        /// <summary>
        /// 获取登录方式
        /// </summary>
        /// <param name="userName"></param>
        /// <returns></returns>
        private string GetUserLoginForm(string userName)
        {
            if (Regex.IsMatch(userName, @"^[1]+[3,4,5,7,8]+\d{9}"))
            {
                return "phone";
            }
            if (Regex.IsMatch(userName, @"^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$"))
            {
                return "email";
            }
            return "usercode";
        }
        /// <summary>
        /// 用户登录
        /// </summary>
        /// <param name="messageInfo"></param>
        /// <returns></returns>
        private ReplyMessage UserLoginSubmit(IAdapter adapter, RequestMessage messageInfo)
        {
            CloudGalleryInfo currentGallery = new GalleryManager().GetGallery(GalleryManager.GetCurrentGalleryId().ToString());
            Dictionary<string, string> contentDic = JsonHelper.ToObject<Dictionary<string, string>>(messageInfo.MessageContent);
            if (!contentDic.ContainsKey("spaceid"))
            {
                contentDic.Add("spaceid", currentGallery.ClientId);
            }
            if (!contentDic.ContainsKey("logintypenew"))
            {
                contentDic.Add("logintypenew", "usercode");
            }
            if (!contentDic.ContainsKey("userip"))
            {
                string ipreg = @"((?:(?:25[0-5]|2[0-4]\d|((1\d{2})|([1-9]?\d)))\.){3}(?:25[0-5]|2[0-4]\d|((1\d{2})|([1-9]?\d))))";
                string hostname = Dns.GetHostName();
                bool getIpFlag = false;
                IPHostEntry localhost = Dns.GetHostEntry(hostname);
                foreach (IPAddress item in localhost.AddressList)
                {
                    if (Regex.IsMatch(item.ToString(), ipreg))
                    {
                        contentDic.Add("userip", item.ToString());
                        getIpFlag = true;
                        break;
                    }
                }
                if (!getIpFlag)
                {
                    contentDic.Add("userip", localhost.AddressList.Last().ToString());
                }
            }
            messageInfo.MessageContent = JsonHelper.ToJson(contentDic);
            ReplyMessage replyMessage = adapter.SubmitRequest(messageInfo);
            if (replyMessage.ReplyMode <= (ReplyModeEnum)0)
            {
                replyMessage.MessageId = messageInfo.MessageId;
            }
            else
            {
                currentGallery.IsLogin = true;
                currentGallery.ClientInfo.SessionId = JsonHelper.ReadJsonString(replyMessage.ReplyContent, "sessionID");
                currentGallery.ClientInfo.UserName = JsonHelper.ReadJsonString(replyMessage.ReplyContent, "user_name");
                currentGallery.ClientInfo.UserCode = replyMessage.ReplyContent.Contains("userCode") ? JsonHelper.ReadJsonString(replyMessage.ReplyContent, "userCode") : JsonHelper.ReadJsonString(replyMessage.ReplyContent, "userCode");
                messageInfo.MessageContent = replyMessage.ReplyContent;
                replyMessage = GetLoginUserRoleSubmit(adapter, messageInfo);
            }
            return replyMessage;
        }
        /// <summary>
        /// 常规消息
        /// </summary>
        /// <param name="adapter"></param>
        /// <param name="messageInfo"></param>
        /// <returns></returns>
        private ReplyMessage MessageSubmit(IAdapter adapter, RequestMessage messageInfo)
        {
            MessageOrganizeManager organizeManager = new MessageOrganizeManager();
            DataOperateEnum saveDataFlag = DataOperateEnum.NONE;
            string DataChannelId = JsonHelper.ReadJsonString(messageInfo.MessageContent, "DataChannelId");
            messageInfo = organizeManager.OrganizeMessage(messageInfo, out saveDataFlag);
            string DataSource = ConfigurationManager.AppSettings.Get("DataSource").ToLower();
            ReplyMessage replyMessage = new ReplyMessage();
            if (saveDataFlag != DataOperateEnum.CANNEL)
            {
                switch (DataSource)
                {
                    case "local":
                        SimulatedDataManager simDataManager = new SimulatedDataManager();
                        replyMessage = simDataManager.SubmitRequest(messageInfo);
                        break;
                    case "remote":
                    default:
                        replyMessage = adapter.SubmitRequest(messageInfo);
                        break;
                }
                if (!(replyMessage.ReplyMode == (ReplyModeEnum)0))
                {
                    ReplyMessageResolver replyMessageResolver = new ReplyMessageResolver();
                    switch (saveDataFlag)
                    {
                        case DataOperateEnum.SAVE:
                            replyMessage = replyMessageResolver.ResolveReplyMessage(replyMessage, messageInfo);
                            break;
                        case DataOperateEnum.COMMIT:
                            bool result = replyMessageResolver.CommitDataSetChange(DataChannelId);
                            break;
                        case DataOperateEnum.NONE:
                        default:
                            break;
                    }
                }
            }
            else
            {
                replyMessage.ReplyMode = 0;
                replyMessage.ReplyAlertMessage = "请先登录";
            }
            if (string.IsNullOrEmpty(replyMessage.ReplyAlertMessage))
            {
                replyMessage.ReplyAlertMessage = JsonHelper.ReadJsonString(replyMessage.ReplyContent, "Result");
            }
            replyMessage.MessageId = messageInfo.MessageId;
            return replyMessage;
        }

        /// <summary>
        /// 获取登陆用户信息的角色
        /// </summary>
        /// <param name="adapter"></param>
        /// <param name="messageInfo"></param>
        /// <returns></returns>
        private ReplyMessage GetLoginUserRoleSubmit(IAdapter adapter, RequestMessage messageInfo)
        {
            GalleryManager galleryManager = new GalleryManager();
            CloudGalleryInfo cloudGallyInfo = galleryManager.GetGallery(GalleryManager.GetCurrentGalleryId().ToString());
            LoginUserInfoModel loginUserInfo = cloudGallyInfo.ClientInfo;
            messageInfo.MessageType = "MongoDataChannelService.getuserroleInfo";
            Dictionary<string, object> contentDic = new Dictionary<string, object>();
            contentDic.Add("systemid", ConfigurationManager.AppSettings["clientsystem"]);
            contentDic.Add("productid", cloudGallyInfo.ClientId);
            string userCode = messageInfo.MessageContent.Contains("usercode") ? JsonHelper.ReadJsonString(messageInfo.MessageContent, "usercode") : JsonHelper.ReadJsonString(messageInfo.MessageContent, "userCode");
            contentDic.Add("usercode", userCode);
            messageInfo.MessageContent = JsonHelper.ToJson(contentDic);
            DataOperateEnum saveDataFlag = DataOperateEnum.NONE;
            MessageOrganizeManager organizeManager = new MessageOrganizeManager();
            messageInfo = organizeManager.OrganizeMessage(messageInfo, out saveDataFlag);
            ReplyMessage replyMessage = adapter.SubmitRequest(messageInfo);
            if (replyMessage.ReplyMode == (ReplyModeEnum)0)
            {
                replyMessage.ReplyAlertMessage = "获取当前登录用户角色失败";
            }
            else
            {
                if (!string.IsNullOrEmpty(replyMessage.ReplyContent))
                {
                    #region 用户信息管理
                    string userInfoStr = JsonHelper.ReadJsonString(replyMessage.ReplyContent, "user");
                    UserBaseInfoModel userInfoModel = JsonHelper.ToObject<UserBaseInfoModel>(userInfoStr);
                    CloudGalleryInfo currentGallery = new GalleryManager().GetGallery(GalleryManager.GetCurrentGalleryId().ToString());
                    try
                    {
                        if (userInfoModel != null)
                        {
                            currentGallery.ClientInfo.CurrentUserInfo = userInfoModel;
                        }
                        else
                        {
                            currentGallery.ClientInfo.CurrentUserInfo = null;
                        }
                    }
                    catch (Exception ex)
                    {
                        LoggerHelper.ErrorFormat("用户信息:{0}", userInfoStr);
                        currentGallery.ClientInfo.CurrentUserInfo = null;
                    }
                    #endregion
                }
            }
            return replyMessage;
        }
        /// <summary>
        /// 获取登录用户选定角色的菜单
        /// </summary>
        /// <param name="adapter"></param>
        /// <param name="messageInfo"></param>
        /// <returns></returns>
        private ReplyMessage GetUserMenuInfoSubmit(IAdapter adapter, RequestMessage messageInfo)
        {
            ReplyMessage replyMessage = adapter.SubmitRequest(messageInfo);
            if (replyMessage.ReplyMode != 0)
            {
                BaseResourceInfo baseResourceInfo = new BaseResourceInfo();
                baseResourceInfo.GalleryId = GalleryManager.GetCurrentGalleryId();
                baseResourceInfo.ResourceXml = replyMessage.ReplyContent;
                CloudGalleryInfo currentGallery = new GalleryManager().GetGallery(GalleryManager.GetCurrentGalleryId().ToString());
                List<MenuInfo> menuInfo = JsonHelper.ToObject<List<MenuInfo>>(JsonHelper.ReadJsonString(replyMessage.ReplyContent, "menus"));
                baseResourceInfo.ResourceMnenus = menuInfo;
                currentGallery.ClientInfo.UserParams = JsonHelper.ToObject<Dictionary<string, object>>(JsonHelper.ReadJsonString(replyMessage.ReplyContent, "params"));
                BaseResourceManager baseResourceManager = new BaseResourceManager();
                bool result = baseResourceManager.AddResouce(baseResourceInfo);
            }
            return replyMessage;
        }
    }
}

