//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Victop.Frame.CoreLibrary.VicException
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Victop.Frame.CoreLibrary.Models;

	/// <summary>
	/// 无接收者异常
	/// </summary>
	public class NoReceiptException:Exception
	{
        private static string ExceptionMsg = "消息没有指明目的地的信息";

		public NoReceiptException():base(ExceptionMsg)
		{
		}

		public NoReceiptException(string exceptionMsg):base(ExceptionMsg+","+exceptionMsg)
		{
		}

		public NoReceiptException(Exception innerException):base(ExceptionMsg,innerException)
		{
		}
        public NoReceiptException(RequestMessage msg)
            : this(msg, null)
        { }
        public NoReceiptException(RequestMessage exceptonMsg, Exception innerException)
            : base(exceptonMsg + "，消息类型：" + exceptonMsg.MessageType + "，消息ID：" + exceptonMsg.MessageId, innerException)
		{
		}

	}
}

