//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Victop.Frame.Component.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Victop.Frame.Component.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///		&quot;views&quot;: [
        ///			{
        ///				&quot;viewname&quot;: &quot;firstview&quot;,
        ///				&quot;modelid&quot;: &quot;&quot;,
        ///				&quot;datafilename&quot;: &quot;&quot;,
        ///				&quot;blocks&quot;: [
        ///					{
        ///						&quot;blockName&quot;: &quot;tom&quot;,
        ///						&quot;blocktype&quot;: &quot;block&quot;,
        ///						&quot;dataSetType&quot;: &quot;table&quot;,
        ///						&quot;superiors&quot;: &quot;root&quot;
        ///					}
        ///				]
        ///			}
        ///		],
        ///		&quot;plugins&quot;: [
        ///			{
        ///				&quot;pluginName&quot;: &quot;firstplugin&quot;,
        ///				&quot;pluginType&quot;: &quot;grid&quot;,
        ///				&quot;dataBlock&quot;: &quot;tom&quot;,
        ///				&quot;Params&quot;: [
        ///					&quot;param1&quot;, &quot;param2&quot;, &quot;param3&quot;
        ///				]
        ///			}
        ///		],
        ///		&quot;compoSetting&quot;: [
        ///			&quot;param7&quot;, &quot;param8&quot;, &quot;param9&quot;
        ///		],
        ///		&quot;paramM [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CompntDataGrid_Def {
            get {
                return ResourceManager.GetString("CompntDataGrid_Def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///		&quot;compoSetting&quot;: {
        ///			&quot;param7&quot;: &quot;el&quot;,
        ///			&quot;param8&quot;: &quot;assembly&quot;,
        ///			&quot;param9&quot;: &quot;jsonData&quot;
        ///		},
        ///		&quot;pluginsSetting&quot;: {
        ///			&quot;firstplugin&quot;: {
        ///				&quot;param1&quot;: &quot;每一个插件需要若干个参数,这里为每一个参数提供设置模版&quot;,
        ///				&quot;param2&quot;: &quot;每一个,一个&quot;,
        ///				&quot;param3&quot;: &quot;天佑中华&quot;
        ///			}
        ///		},
        ///		&quot;viewSetting&quot;: {
        ///			&quot;views&quot;: {
        ///				&quot;firstview&quot;: {
        ///					&quot;modelid&quot;: &quot;victop_core_requirement_pool_0001&quot;,
        ///					&quot;datafilename&quot;: &quot;data.json&quot;,
        ///					&quot;blocks&quot;: {
        ///						&quot;tom&quot;: {
        ///							&quot;tablename&quot;: &quot;iteration&quot;
        ///						}
        ///					}
        ///				}
        ///			}
        ///		}
        ///	} 的本地化字符串。
        /// </summary>
        internal static string CompntDataGrid_Setting {
            get {
                return ResourceManager.GetString("CompntDataGrid_Setting", resourceCulture);
            }
        }
    }
}
